add works section
mj-e-boc/MJ-Portfolio pull request #3
Opened 2022-07-01 14:10 UTC by mj-e-boc

-Add works Section

2022-07-01 16:22 UTC, 1GORDON requested changes
##
## Hi @mj-e-boc ✋

Good job so far!

## Highlights!
- Followed Git flow ✔️ 
- Good commit messages  ✔️ 
- Professional Readme ✔️
- Professional Pull request ✔️
- Great use of semantic tags ✔️
- Project is working as expected ✔️
- Linters are passing ✔️    

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 16:22 UTC, 1GORDON commented on index.html
>              <li class="bars"><i class="fa-solid fa-bars"></i></li>
Great work @mj-e-boc🤝

- [ ] [Optional] Try to make the hamburger icon a clickable link. You may surround it with an `<a>` tag

2022-07-01 16:22 UTC, 1GORDON commented on styles.css
> +}
Great work @mj-e-boc 🤝

- [ ] As pointed out in the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md). You may please implement the button interactions hover and enable.

2022-07-01 16:22 UTC, 1GORDON commented on styles.css
>  }
Nice design @mj-e-boc 🤝

- [ ] You may please try to use the right font-family as it is provided in the Figma template.

2022-07-02 19:20 UTC, rloterh commented on index.html
> +    <div class="bod">
This issue is well resolved! ✔️

2022-07-02 19:20 UTC, rloterh commented on index.html
> +            <button class="button" type="button">see Project</button>
This issue is well resolved! ✔️

2022-07-02 19:20 UTC, rloterh commented on index.html
>              <li class="bars"><i class="fa-solid fa-bars"></i></li>
This issue is well resolved! ✔️

2022-07-02 19:20 UTC, rloterh commented on styles.css
> +}
This issue is well resolved! ✔️

2022-07-02 19:20 UTC, rloterh commented on styles.css
>  }
This issue is well resolved! ✔️

2022-07-02 19:22 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi ,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Highlights 👍
- App matches design template


<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 19:31 UTC, merged

2023-01-18 11:55 UTC, GedeonTS reviewed
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @mj-e-boc,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
- No linter errors :clamp: 
- Good use of GitHub flow
## Optional suggestions :small_airplane: 
- [OPTIONAL] I think it would be better to write a more descriptive PR summary, as it would ma ke your project look more professional

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._